name: Merge and Delete branch after approval

on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  state_event_type:
    runs-on: ubuntu-latest
    steps:
      - name: if_pr
        if: github.event.pull_request.merged == 'true'
        run: |
          echo A pull request was closed
