name: Merge and Delete branch after approval

on:
  pull_request:
    types:
      - closed

jobs:
  state_event_type:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload
        run: |
          echo "Payload: ${{ toJson(github.event) }}"

      - name: Check if PR was merged
        if: github.event.pull_request.merged_at != null
        run: |
          echo "A pull request was merged to the main branch."

      - name: Delete branch after being merged to main
        if: github.event.pull_request.merged_at != null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the branch name from the event payload
          branch_name="${{ github.event.pull_request.head.ref }}"
          echo "Deleting branch: $branch_name"

          # Authenticate and delete the branch
          echo "${GITHUB_TOKEN}" | gh auth login --with-token
          gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/$branch_name
